<?php $this->headTitle('XSS'); ?>
<h1><span class="mezzio-green"><?= $this->title ?></span></h1>
<div class="jumbotron">
    <h1>Interesting Article</h1>
    <p>
        Contrary to popular belief, Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC,
        making it over 2000 years old. Richard McClintock, a Latin professor at Hampden-Sydney College in Virginia, looked up one of the more obscure Latin words, consectetur,
        from a Lorem Ipsum passage, and going through the cites of the word in classical literature, discovered the undoubtable source. Lorem Ipsum comes from sections 1.10.32
        and 1.10.33 of "de Finibus Bonorum et Malorum" (The Extremes of Good and Evil) by Cicero, written in 45 BC. This book is a treatise on the theory of ethics, very popular
        during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
    </p>
</div>
<h2>Enter Comments on the article</h2>
<div class="jumbotron">
    <div>
        <?php $this->form()->openTag($this->commentForm) ?>
        <div class="form-group">
            <?= $this->formLabel($this->commentForm->get('fullName')) ?>
            <?= $this->formElement($this->commentForm->get('fullName')) ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($this->commentForm->get('comment')) ?>
            <?= $this->formElement($this->commentForm->get('comment')) ?>
        </div>
        <div class="form-group">
            <button type="button" class="btn btn-primary float-right">Submit</button>
        </div>
        <?= $this->form()->closeTag($this->form) ?>
    </div>
</div>