<?php $this->headTitle('XSS'); ?>
<h1><span class="mezzio-green"><?= $this->title ?></span></h1>
<div class="jumbotron">
    <h1>Interesting Article</h1>
    <p>
        Contrary to popular belief,
        Dui faucibus in ornare quam. Ac turpis egestas integer eget aliquet nibh praesent. Tristique senectus et netus et malesuada fames.
        Amet luctus venenatis lectus magna fringilla urna porttitor rhoncus. Ut faucibus pulvinar elementum integer enim neque volutpat.
        Tellus orci ac auctor augue. Consectetur purus ut faucibus pulvinar. Quis eleifend quam adipiscing vitae proin sagittis nisl rhoncus mattis. Sagittis nisl rhoncus mattis rhoncus.
        Ac feugiat sed lectus vestibulum. Eget nulla facilisi etiam dignissim diam quis enim. Porttitor rhoncus dolor purus non enim praesent elementum. Imperdiet nulla malesuada
        pellentesque elit eget gravida. Enim diam vulputate ut pharetra sit amet. Ullamcorper sit amet risus nullam eget. Fermentum dui faucibus in ornare. Mattis vulputate enim nulla aliquet porttitor. Pharetra diam sit amet
        nisl suscipit adipiscing bibendum est ultricies. Fusce id velit ut tortor pretium viverra suspendisse potenti. Massa tincidunt nunc pulvinar sapien et ligula ullamcorper malesuada proin.
    </p>
    <p>
        Lorem Ipsum is not simply random text. It has roots in a piece of classical Latin literature from 45 BC,Tempus imperdiet nulla malesuada pellentesque. Morbi quis commodo odio aenean sed adipiscing diam.
        Fringilla urna porttitor rhoncus dolor purus. Gravida in fermentum et sollicitudin ac orci phasellus egestas. Cras sed felis eget velit aliquet sagittis id. Mattis rhoncus urna neque viverra justo nec ultrices.
        Mauris sit amet massa vitae tortor condimentum. Et odio pellentesque diam volutpat commodo sed egestas egestas fringilla. In cursus turpis massa tincidunt. Vulputate ut pharetra sit amet aliquam id diam maecenas.
        Posuere sollicitudin aliquam ultrices sagittis orci. Non pulvinar neque laoreet suspendisse interdum consectetur. Id venenatis aThis book is a treatise on the theory of ethics, very popular
        during the Renaissance. The first line of Lorem Ipsum, "Lorem ipsum dolor sit amet..", comes from a line in section 1.10.32.
    </p>
</div>
<h2>Enter Comments on the article</h2>
<div class="jumbotron">
    <div>
        <?php $this->form()->openTag($this->commentForm) ?>
        <div class="form-group">
            <?= $this->formLabel($this->commentForm->get('fullName')) ?>
            <?= $this->formElement($this->commentForm->get('fullName')) ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($this->commentForm->get('comment')) ?>
            <?= $this->formElement($this->commentForm->get('comment')) ?>
        </div>
        <div class="form-group">
            <button type="button" class="btn btn-primary float-right">Submit</button>
        </div>
        <?= $this->form()->closeTag($this->commentForm) ?>
    </div>
</div>